name: "Release Tag"
on:
  workflow_run:
    workflows: [ "Publish Packages" ]
    types:
      - completed
jobs:
  create-release-tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' && !contains(github.event.head_commit.message, 'skip ci')}}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate Jar
        run: |
          mvn clean package -DskipTests
          ls -la ./target

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN:  ${{ github.token }}
        with:
          tag_name: ${{ steps.previoustag.outputs.tag }}
          release_name: Release ${{ steps.previoustag.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN:  ${{ github.token }}
        with:
          tag_name: ${{ steps.previoustag.outputs.tag }}
          name: Release ${{ steps.previoustag.outputs.tag }}
          files: './target/*.jar'